getBits: getBits.c
        gcc -o getBits getBits.c
getBits: getBits.c
        gcc -o getBits getBits.c
getBits: getBits.c
        gcc -o getBits getBits.c
getBits: getBits.c
        gcc -o getBits getBits.c
getBits: getBits.c
        gcc -o getBits getBits.c
getBits: getBits.c
        gcc -o getBits getBits.c
getBits: getBits.c
	gcc -o getBits getBits.c
